version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $REPO_DOMAIN
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t multi-tenant-architecture-nestjs .
      - docker tag multi-tenant-architecture-nestjs:latest 929301630441.dkr.ecr.us-east-1.amazonaws.com/multi-tenant-architecture-nestjs:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push 929301630441.dkr.ecr.us-east-1.amazonaws.com/multi-tenant-architecture-nestjs:latest
      - echo Writing image definitions file...
      - printf '[{"name":"multi-tenant-architecture","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
artifacts:
  files: imagedefinitions.json
